### PR TITLE
engine.h cleanup

### PR DESCRIPTION
**Pull request by mtlll**
Splitting out all function prototypes from engine.h(except ones for main.cpp) into new or existing headers corresponding to the .cpp they're implemented in. Also removed all the externs and removed and inline that was causing compilation errors.

I've been thinking, we should maybe divide all these files in the engine directory into various subdirectories? Like octa/ render/ materials/ etc. I'm not an expert on game engines so I could use some input on where to put things.

### CODE REVIEW

**Comment by WatIsDeze** [comment]
Currently stuck with a mobile phone ISP, so I sadly can't test this. I've asked @Micha0  to do a review.

As for the folder question, that is indeed what I had in mind as well. I'm almost 100% sure that @Micha0 would agree to this as well. So by all means, you got a green light for that one.

**Comment by Micha0** [comment]
gooood job!
this still compiles ok?

**Comment by mtlll** [comment]
It compiles on my machine anyway, but you might wanna run a test build anyway, you never know :)

**Comment by Micha0** [comment]
worked like a charm, first time!

**Pull request merged**
